### ISSUE TITLE
Update AWS SDK

### ISSUE THREAD

**Issue by pcfens** [deliciousbrains/wp-offload-ses-lite#16]
This issue is essentially the same as deliciousbrains/wp-amazon-s3-and-cloudfront#536. The same benefit of using an IAM role should work here too.

I'm attempting to use IAM roles linked to a Kubernetes service account to grant access to S3 instead of giving the entire node an IAM role. Amazon's documentation says that version 3.110.7 or newer of the PHP SDK is required. There have been bugfixes since then, so an update to the latest PHP SDK would be appreciated.

**Comment by runningman84** [comment]
@ianmjones could you please add the sts client and sdk update here too?

**Comment by viktorhaid** [comment]
Hi, any plans on when it will be fixed here? As it was patched already in the media offload plugin.

**Comment by runningman84** [comment]
@mattgrshaw did the 1.4.4 update include the latest aws sdk?

**Comment by mattgrshaw** [comment]
@runningman84 yep, the last release updated the SDK to the current version at the time (Dec. 2020).
