### ISSUE TITLE
How can I `composer require` this package? 

### ISSUE THREAD

**Issue by rehanvdm** [deliciousbrains/wp-offload-ses-lite#26]
I take it that I can not install it using composer as it actually installs the paid version with limited functionality until you provide the License key? 

I tried various methods but could not install the lite version? Please help? 

I also consulted this
https://deliciousbrains.com/wp-offload-ses/doc/installing-via-composer/

**Comment by polevaultweb** [comment]
For the Lite version, you can install using the wpackagist.org repository. See their instrcutions on adding the custom repository to your composer.json -> https://wpackagist.org/

Then you can do:

`composer require wpackagist-plugin/wp-ses`

**Comment by rehanvdm** [comment]
Thank you :) @polevaultweb
