### ISSUE TITLE
Authentication through IAM instance profile

### ISSUE THREAD

**Issue by ryan-burt** [deliciousbrains/wp-offload-ses-lite#47]
I host my Wordpress server on EC2/ECS
It would be great and inline with AWS security best practices to be able use the credentials attached to the instance rather than access keys. 

Is this something being worked on?

**Comment by ianmjones** [comment]
This is already possible. :tada: 

https://deliciousbrains.com/wp-offload-ses/doc/iam-roles/

Basically just add following to `wp-config.php`:

```php
define( 'WPOSES_AWS_USE_EC2_IAM_ROLE', true );
```

**Comment by ryan-burt** [comment]
Awesome, thanks for the link Ian.
I tried Googling with a couple of different phrases before posting this issue so I'm not sure how I missed that page.
